services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:3000"
    volumes:
      - ".:/app"
    environment:
      - API_URL=${API_URL}
